"""phase 4: pages combined-fix columns

Revision ID: 06c057e5a1fc
Revises: 92f78d8d9d6b
Create Date: 2026-07-10 00:23:40.407789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c057e5a1fc'
down_revision: Union[str, Sequence[str], None] = '92f78d8d9d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('fixed_html_snapshot_path', sa.String(length=1024), nullable=True))
    op.add_column('pages', sa.Column('combined_verification_status', sa.String(length=20), nullable=True))
    op.add_column('pages', sa.Column('combined_verification_detail', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('combined_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'combined_verified_at')
    op.drop_column('pages', 'combined_verification_detail')
    op.drop_column('pages', 'combined_verification_status')
    op.drop_column('pages', 'fixed_html_snapshot_path')
    # ### end Alembic commands ###
