"""phase 2: llm_call_logs mock/error columns, llm_response_cache table

Revision ID: 347a304e5105
Revises: f2c8003c7e94
Create Date: 2026-07-06 17:53:47.246727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347a304e5105'
down_revision: Union[str, Sequence[str], None] = 'f2c8003c7e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_response_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wcag_rule', sa.String(length=100), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_response_cache_cache_key'), 'llm_response_cache', ['cache_key'], unique=True)
    op.add_column('llm_call_logs', sa.Column('is_mock', sa.Boolean(), nullable=False))
    op.add_column('llm_call_logs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('llm_call_logs', sa.Column('error_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call_logs', 'error_type')
    op.drop_column('llm_call_logs', 'error')
    op.drop_column('llm_call_logs', 'is_mock')
    op.drop_index(op.f('ix_llm_response_cache_cache_key'), table_name='llm_response_cache')
    op.drop_table('llm_response_cache')
    # ### end Alembic commands ###
