"""phase 2.6: violations.detection_confidence

Revision ID: 92f78d8d9d6b
Revises: 347a304e5105
Create Date: 2026-07-08 02:42:58.809674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f78d8d9d6b'
down_revision: Union[str, Sequence[str], None] = '347a304e5105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('detection_confidence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'detection_confidence')
    # ### end Alembic commands ###
