"""phase 5 session 6: llm_call_logs retry_after_s column

Revision ID: a6aa4dda4adb
Revises: 06c057e5a1fc
Create Date: 2026-07-26 13:13:52.796651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6aa4dda4adb'
down_revision: Union[str, Sequence[str], None] = '06c057e5a1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call_logs', sa.Column('retry_after_s', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call_logs', 'retry_after_s')
    # ### end Alembic commands ###
