"""initial schema: 8 tables per docs/schema.md

Revision ID: f2c8003c7e94
Revises: 
Create Date: 2026-07-05 04:02:44.242467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c8003c7e94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.Enum('Reviewer', 'Impact', 'Developer', 'Verifier', name='agent_name'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_url'), 'sites', ['url'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='scan_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('raw_html_snapshot_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('wcag_rule', sa.String(length=100), nullable=False),
    sa.Column('element_selector', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('open', 'fixed', 'rejected', name='violation_status'), nullable=False),
    sa.Column('html_snippet', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('proposed_code_diff', sa.Text(), nullable=True),
    sa.Column('target_selector', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'rejected', 'manual_review', name='fix_verification_status'), nullable=True),
    sa.Column('failure_reason', sa.Enum('invalid_html', 'dom_changed', 'playwright_timeout', 'diff_failed_to_apply', name='fix_failure_reason'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('is_critical_path', sa.Boolean(), nullable=False),
    sa.Column('reasoning_text', sa.Text(), nullable=True),
    sa.Column('business_risk_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fix_id', sa.Integer(), nullable=False),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='approval_decision'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('pr_status', sa.Enum('created', 'merged', 'rejected', 'pending', name='pr_status'), nullable=True),
    sa.ForeignKeyConstraint(['fix_id'], ['fixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_table('impact_assessments')
    op.drop_table('fixes')
    op.drop_table('violations')
    op.drop_table('pages')
    op.drop_table('scans')
    op.drop_index(op.f('ix_sites_url'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###

    # Manually added — autogenerate's drop_table() calls above don't drop the
    # Postgres ENUM types those columns used (CREATE TYPE is a separate DDL
    # statement from CREATE TABLE, and alembic autogenerate doesn't emit the
    # matching DROP TYPE on downgrade). Without this, a downgrade followed by
    # another upgrade fails with "type already exists" the moment
    # create_table tries to recreate a table using one of these enums.
    bind = op.get_bind()
    sa.Enum(name='agent_name').drop(bind, checkfirst=True)
    sa.Enum(name='scan_status').drop(bind, checkfirst=True)
    sa.Enum(name='violation_status').drop(bind, checkfirst=True)
    sa.Enum(name='fix_verification_status').drop(bind, checkfirst=True)
    sa.Enum(name='fix_failure_reason').drop(bind, checkfirst=True)
    sa.Enum(name='approval_decision').drop(bind, checkfirst=True)
    sa.Enum(name='pr_status').drop(bind, checkfirst=True)
